
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Providers } from "./Providers";

export const metadata: Metadata = {
  title: "Notecast - Your AI-Powered Note-Taking Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
