
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Providers } from "./Providers";
import { Toaster } from 'react-hot-toast';
import {
  ClerkProvider
} from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "Notecast - Your AI-Powered Note-Taking Assistant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
     <ClerkProvider>
    <html lang="en">
      <body className="dark">
        <Toaster />
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
    </ClerkProvider>
  );
}
